Repository Azure/data-management-zone, pull requests merged in 2021-11, with the labels that each got.

#217 Updated Network Doc
  docs/guidance/EnterpriseScaleAnalytics-NetworkArchitecture.md
Labels: documentation

#220 Updated Codeowners
  .github/CODEOWNERS
Labels: enhancement

#224 Updated Azure CLI Version
  .github/workflows/dataManagementZoneDeployment.yml
Labels: bug, committed

#228 Azure CLI Action Bugfix
  .github/workflows/dataManagementZoneDeployment.yml
Labels: bug, committed

#231 Purview default deployment region update
  .github/linters/.markdown-lint.yml
  docs/EnterpriseScaleAnalytics-Prerequisites.md
Labels: documentation

#230 Fix ESA Deployment Bug
  docs/reference/enterpriseScaleAnalytics.bicep
  docs/reference/enterpriseScaleAnalytics.json
Labels: bug, committed

#232 Update EnterpriseScaleAnalytics-ServicePrincipal.md
  docs/EnterpriseScaleAnalytics-ServicePrincipal.md
Labels: documentation

#225 Updated Docs for ADO and GitHub Deployment
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
Labels: documentation

#233 Update EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
Labels: documentation

#234 Added Synapse Kusto Policy
  .github/workflows/lint.yml
  infra/Policies/PolicyDefinitions/Synapse/params.policyDefinition.Deny-Synapse-Kusto-OptimizedAutoscale.json
Labels: feature, committed

#235 Updated Docs for consistency
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  docs/EnterpriseScaleAnalytics-ServicePrincipal.md
Labels: documentation

#236 Added Option to Select VM Image
  docs/reference/bastionhost/main.bicep
  docs/reference/bastionhost/main.json
  docs/reference/bastionhost/modules/bastion.bicep
  docs/reference/bastionhost/modules/services/virtualmachine.bicep
  docs/reference/bastionhost/portal.json
Labels: feature, committed

#237 Updated Bastion Architecture Image
  docs/images/AzureBastionArchitecture.png
Labels: documentation, committed

#204 Added Doc about Scaling and Self-Service in ESA
  docs/guidance/EnterpriseScaleAnalytics-SelfService.md
  docs/images/MultipleLandingZones.png
Labels: documentation
