Repository Azure/data-management-zone, pull requests merged in 2021-12, with the labels that each got.

#246 Updated Network Doc
  docs/guidance/EnterpriseScaleAnalytics-NetworkArchitecture.md
Labels: documentation, committed

#240 Updated to Win11 and Updated AIO Deployment Parameters
  docs/reference/bastionhost/main.bicep
  docs/reference/bastionhost/main.json
  docs/reference/bastionhost/modules/bastion.bicep
  docs/reference/bastionhost/modules/services/virtualmachine.bicep
  docs/reference/bastionhost/portal.json
  docs/reference/enterpriseScaleAnalytics.bicep
  docs/reference/enterpriseScaleAnalytics.json
  docs/reference/portal.enterpriseScaleAnalytics.json
Labels: enhancement, committed

#247 Updated Cost Calculator Links
  docs/guidance/EnterpriseScaleAnalytics-CostEstimates.md
Labels: documentation, committed

#243 Updated ESA Scale Document
  docs/guidance/EnterpriseScaleAnalytics-SelfService.md
Labels: documentation

#251 Updated Policy for Data Explorer
  infra/Policies/PolicyDefinitions/DataExplorer/params.policyDefinition.Deny-DataExplorer-TrustedExternalTenants.json
Labels: bug, committed

#245 Renaming ESA to DMA
  README.md
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-CreateRepository.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/DataManagementAnalytics-KnownIssues.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/DataManagementAnalytics-ServicePrincipal.md
  docs/guidance/DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
  docs/guidance/DataManagementAnalytics-CostEstimates.md
  docs/guidance/DataManagementAnalytics-LimitingCrossTenantPrivateEndpointProvisioning.md
  docs/guidance/DataManagementAnalytics-NetworkArchitecture.md
  docs/guidance/DataManagementAnalytics-Policies.md
  docs/guidance/DataManagementAnalytics-SelfHostedCiCdAgents.md
  docs/guidance/DataManagementAnalytics-SelfService.md
  docs/images/DataManagementAnalytics.gif
  docs/images/EnterpriseScaleAnalytics.gif
  docs/reference/bastionhost/main.bicep
  docs/reference/bastionhost/main.json
  docs/reference/bastionhost/portal.json
  docs/reference/buildagents/main.bicep
  docs/reference/buildagents/main.json
  docs/reference/buildagents/portal.json
  docs/reference/dataManagementAnalytics.bicep
  docs/reference/dataManagementAnalytics.json
  docs/reference/portal.dataManagementAnalytics.json
  docs/reference/portal.dataManagementZone.json
  infra/main.bicep
  infra/main.json
Labels: documentation

#253 Fix All-in-one Template Bug
  docs/reference/dataManagementAnalytics.bicep
  docs/reference/dataManagementAnalytics.json
Labels: bug, committed

#255 New Issue/PR Templates & New Contributors Guide
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/linters/.textlintrc
  CONTRIBUTING.md
  README.md
Labels: documentation, committed

#264 Added guidance on enrolling to Intune for Jumpbox VM in case of corporate policy requirement
  docs/guidance/DataManagementAnalytics-ConnectToEnvironmentsPrivately.md
Labels: documentation

#259 Updated GH Issue and PR Template Links
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#258 Improving Region Availability
  docs/DataManagementAnalytics-Prerequisites.md
  docs/reference/bastionhost/portal.json
  docs/reference/buildagents/portal.json
  docs/reference/portal.dataManagementAnalytics.json
  docs/reference/portal.dataManagementZone.json
  infra/main.json
  infra/modules/network.bicep
  infra/modules/services/purview.bicep
Labels: enhancement
