Repository Azure/data-management-zone, pull requests merged in 2021-09, with the labels that each got.

#150 Added Network Design Considerations
  .github/linters/.markdown-lint.yml
  docs/EnterpriseScaleAnalytics-ServicePrincipal.md
  docs/guidance/EnterpriseScaleAnalytics-NetworkArchitecture.md
  docs/guidance/EnterpriseScaleAnalytics-Policies.md
  docs/images/NetworkOptions-HubAndSpoke.png
  docs/images/NetworkOptions-MeshedNetworkArchitecture.png
  docs/images/NetworkOptions-NetworkMesh.png
  docs/images/NetworkOptions-PrivateEndpointProjection.png
  docs/images/NetworkOptions-PrivateEndpointsInConnectivityHub.png
Labels: documentation

#156 Updated Header Size
  docs/guidance/EnterpriseScaleAnalytics-NetworkArchitecture.md
Labels: documentation

#154 Added Bastion Host Template
  docs/guidance/EnterpriseScaleAnalytics-ConnectToEnvironmentsPrivately.md
  docs/images/AzureBastionArchitecture.png
  docs/images/AzureBastionConnectToVm.png
  docs/images/AzureBastionEnterCredentials.png
  docs/images/AzureBastionNetworkArchitecture.png
  docs/images/AzureBastionResourceGroup.png
  docs/images/AzureBastionSubnets.png
  docs/reference/bastionhost/main.bicep
  docs/reference/bastionhost/main.json
  docs/reference/bastionhost/modules/bastion.bicep
  docs/reference/bastionhost/modules/network.bicep
  docs/reference/bastionhost/modules/services/bastion.bicep
  docs/reference/bastionhost/modules/services/virtualmachine.bicep
  docs/reference/bastionhost/portal.json
  docs/reference/portal.dataManagementZone.json
  infra/main.json
  infra/modules/services/containerregistry.bicep
  infra/modules/services/firewallPolicyRules.bicep
  infra/modules/services/keyvault.bicep
  infra/modules/services/powerbiprivatelink.bicep
  infra/modules/services/purview.bicep
  infra/modules/services/synapseprivatelinkhub.bicep
Labels: enhancement

#158 Adding RP Registration to Portal for Purview
  docs/reference/portal.dataManagementZone.json
  docs/reference/portal.enterpriseScaleAnalytics.json
Labels: enhancement

#160 Adding Known Issue to Doc
  docs/EnterpriseScaleAnalytics-KnownIssues.md
Labels: documentation

#161 Added Purview RP Registration in Portal
  docs/EnterpriseScaleAnalytics-KnownIssues.md
  docs/reference/portal.dataManagementZone.json
  docs/reference/portal.enterpriseScaleAnalytics.json
Labels: documentation, enhancement

#162 Added Portal RP Warning & Updated Purview Regions
  docs/reference/portal.dataManagementZone.json
  docs/reference/portal.enterpriseScaleAnalytics.json
  infra/main.json
  infra/modules/services/purview.bicep
Labels: enhancement

#163 Added more Guidance in Bastion Host Article
  docs/guidance/EnterpriseScaleAnalytics-ConnectToEnvironmentsPrivately.md
Labels: documentation

#165 Added Cost Estimates
  docs/guidance/EnterpriseScaleAnalytics-CostEstimates.md
Labels: documentation

#167 Bugfix in Bastion Host template
  docs/reference/bastionhost/main.json
  docs/reference/bastionhost/modules/services/virtualmachine.bicep
Labels: bug

#168 Typo error - management misspelt as "managememt"
  docs/EnterpriseScaleAnalytics-Prerequisites.md
Labels: documentation

#170 Update Purview Known Error
  docs/EnterpriseScaleAnalytics-KnownIssues.md
Labels: documentation

#171 Fix Linting from Forks
  .github/workflows/lint.yml
Labels: bug, enhancement

#172 Updated Resource Provider Guidance in Portal
  docs/reference/portal.dataManagementZone.json
  docs/reference/portal.enterpriseScaleAnalytics.json
Labels: enhancement

#152 Added Network Cross-Tenant Private Endpoint Guidance
  docs/guidance/EnterpriseScaleAnalytics-LimitingCrossTenantPrivateEndpointProvisioning.md
  docs/images/CrossTenantPrivateEndpointProvisioning.png
Labels: documentation

#173 Update Codeowners
  .github/CODEOWNERS
Labels: enhancement

#174 Fix for known issue - Purview registration
  docs/EnterpriseScaleAnalytics-KnownIssues.md
Labels: documentation

#175 Adding AML Policy to Disable Public Network Access
  infra/Policies/PolicyDefinitions/MachineLearning/params.policyDefinition.Deny-MachineLearning-PublicNetworkAccess.json
Labels: enhancement

#176 Updated Cost Estimate Doc & Added Conclusion to Network Doc
  docs/guidance/EnterpriseScaleAnalytics-CostEstimates.md
  docs/guidance/EnterpriseScaleAnalytics-NetworkArchitecture.md
Labels: documentation

#178 Improve Firewall Rule Definitions and DNS Setup
  .github/linters/.arm-ttk.psd1
  docs/reference/portal.dataManagementZone.json
  infra/main.json
  infra/modules/services/firewallPolicyRules.bicep
Labels: enhancement

#180 Added new AML categories and updated metrics categories
  infra/Policies/PolicyDefinitions/DiagnosticSettings/params.machineLearning.json
Labels: enhancement

#183 Updated Purview Studio DNS Setup
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
  infra/main.bicep
  infra/main.json
  infra/modules/governance.bicep
  infra/modules/services/privatednszones.bicep
  infra/modules/services/purview.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: enhancement
