Repository Azure/data-management-zone, pull requests merged in 2022-01, with the labels that each got.

#267 Add Data Landing Zone Subs as Input
  .github/linters/.arm-ttk.psd1
  docs/reference/dataManagementAnalytics.bicep
  docs/reference/dataManagementAnalytics.json
Labels: feature, committed

#269 Rename Data Management Zone
  README.md
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-CreateRepository.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/DataManagementAnalytics-KnownIssues.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/DataManagementAnalytics-ServicePrincipal.md
Labels: documentation

#219 New Network Capabilities
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/reference/dataManagementAnalytics.bicep
  docs/reference/dataManagementAnalytics.json
  docs/reference/portal.dataManagementZone.json
  infra/main.bicep
  infra/main.json
  infra/modules/consumption.bicep
  infra/modules/network.bicep
  infra/modules/services/firewallPolicyRules.bicep
  infra/modules/services/purview.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: feature, committed

#272 Fix Portal UI Bug
  docs/reference/bastionhost/portal.json
  docs/reference/buildagents/portal.json
  docs/reference/portal.dataManagementAnalytics.json
Labels: bug

#273 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
